[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/chat"  # Asegúrate de que este endpoint existe en tu backend
healthcheckTimeout = 300

[env]
NODE_VERSION = "16"
PORT = "4000"
