[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT run:app"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
PYTHON_VERSION = "3.9"
NODE_VERSION = "14"