[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT backend.app:app"  # Comando para iniciar la app con gunicorn

[variables]
PORT = 8080  # Asegúrate de que el puerto esté configurado correctamente
