[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn -w 1 -timeout 120 -b 0.0.0.0:4000 app:app"
healthcheckPath = "/health"  # Asegúrate de que este endpoint existe en tu backend
healthcheckTimeout = 300

[env]
NODE_VERSION = "16"
PORT = "4000"