[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:4000"
healthcheckPath = "/chat"  # Asegúrate de que este endpoint existe en tu backend
healthcheckTimeout = 300

[env]
NODE_VERSION = "16"
PORT = "4000"
